name: Despliegue
on:
  workflow_run:
    workflows: ["comprobarApp"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
        - uses: actions/checkout@v4

        - name: Configurar las credenciales de AWS
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-region: "us-east-1"
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            
        - name: Configurar Codedeploy
          run: |
              aws deploy create-deployment \
              --application-name "tomCatApp" \
              --deployment-group-name "tomcatAppGroup" \
              --github-location repository=${{ github.repository }},commitId=${{ github.sha }}